DROP DATABASE IF EXISTS userdb;
DROP USER IF EXISTS `useradmin`@`%`;
DROP USER IF EXISTS `theuser`@`%`;
CREATE DATABASE IF NOT EXISTS userdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `useradmin`@`%` IDENTIFIED BY 'useradmin';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `userdb`.* TO `useradmin`@`%` WITH GRANT OPTION;
-- GRANT ALL ON `userdb`.* TO `useradmin`@`%` WITH GRANT OPTION;
CREATE USER IF NOT EXISTS `theuser`@`%` IDENTIFIED BY 'theuser';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `userdb`.* TO `theuser`@`%`;
-- GRANT ALL ON `userdb`.* TO `theuser`@`%` WITH GRANT OPTION;
FLUSH PRIVILEGES;