#!/bin/bash
# Note: Install httpie tool to run these below commands.
# user-service
# user-service ping GET
echo "ping user-service directly"
http http://localhost:9121/api/users/ping api-key:apikey222

# user-service ping GET via api-gateway
echo "ping user-service via api-gateway"
http http://localhost:9211/api/users/ping api-key:apikey222

## Create user in user-service via api-gateway
#echo "Create a user/Sign-up in user-service via api-gateway"
#http POST http://localhost:9211/api/users/signup \
#  Content-Type:"application/json" \
#  api-key:"apikey222" \
#  firstName="John" \
#  lastName="Smith" \
#  loginId="john.smith@example.com" \
#  password="aSecurePassword123@" \
#  confirmPassword="aSecurePassword123@" \
#  userAgentType="API"

# Create user in user-service via api-gateway
echo "Login/Sign-In a user in user-service via api-gateway"
http POST http://localhost:9211/api/users/signin \
  Content-Type:"application/json" \
  api-key:"apikey222" \
  loginId="john.smith@example.com" \
  password="aSecurePassword123@" \
  userAgentType="API"


# Create role in user-service via api-gateway
#echo "Create a role in user-service via api-gateway"
#http POST http://localhost:9211/api/users/roles \
#  Content-Type:"application/json" \
#  api-key:"apikey222" \
#  role="USER" \
#  description="standard user role"