spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

iam:
  keycloak:
    admin:
      base-url: ${KEYCLOAK_BASE_URL}
      realm: ${KEYCLOAK_REALM}
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
