spring:
  application:
    name: "${SPRING_APP_NAME:user-service}"
  devtools:
    restart:
      enabled: true
  threads:
    virtual:
      enabled: true
  jackson:
    mapper:
      accept-case-insensitive-properties: true
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    sql:
      init:
        mode: always
  datasource:
    username: theuser
    password: theuser
    url: jdbc:mariadb://mariadb:3306/userdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  flyway:
    userDomain: useradmin
    password: useradmin
    sql-migration-prefix: V
    repeatable-sql-migration-prefix: R
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  security:
    userDomain:
      name: "${SECURITY_USERNAME:srikanth}"
      password: "${SECURITY_PASSWORD:srikanth}"
server:
  port: 9121
  servlet:
    session:
      timeout: ${USER_SESSION_TIMEOUT:5m}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
logging:
  level:
    userDomain: debug
    org:
      hibernate: ERROR
      hibernate.type.descriptor.sql: trace
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    level: ${LOGPATTERN_CONSOLE:%green(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %blue(-%5level) %red([%thread]) %magenta(---){faint} %yellow(%logger{15}) - %msg%n}
management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, env, metrics, auditevents, httptrace, loggers, threaddump
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
    java:
      enabled: true
    os:
      enabled: true
info:
  app:
    name: "${spring.application.name}"
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
  show-actuator: true
JWT_EXPIRY_TTL: 70000
apiKey: apikey111,apikey222